"""
$ pip install pillow numpy
Builds the karma spinner WebP strip and outputs karmaSpinnerData.ts.
Edit FRAMES to change which symbols are included and their karma level identifiers.
Run from the repo root: python scripts/build-spinner.py
"""

from PIL import Image
import numpy as np, io, base64, os

KARMA_DIR = 'scripts/karma'
OUTPUT_TS  = 'site/src/app/components/karmaSpinnerData.ts'

# (source filename, index)
FRAMES = [
    ("karma10.png", 1),
    ("karma20.png", 2),
    ("karma30.png", 3),
    ("karma40.png", 4),
    ("karma50.png", 5),
    ("karma64.png", 6),
    ("karma74.png", 7),
    ("karma84.png", 8),
    ("karma94.png", 9),
    ("karmaA0.png", 10),
]

imgs = [Image.open(os.path.join(KARMA_DIR, filename)).convert('RGBA') for filename, _ in FRAMES]

frame_size = max(max(img.width for img in imgs), max(img.height for img in imgs))

# Pad any frames smaller than frame_size with transparent pixels (centered)
uniform = []
for img in imgs:
    if img.width == frame_size and img.height == frame_size:
        uniform.append(img)
    else:
        cell = Image.new('RGBA', (frame_size, frame_size), (0, 0, 0, 0))
        cell.paste(img, ((frame_size - img.width) // 2, (frame_size - img.height) // 2))
        uniform.append(cell)

strip = Image.new('RGBA', (frame_size * len(uniform), frame_size))
for i, f in enumerate(uniform):
    strip.paste(f, (i * frame_size, 0))

buf = io.BytesIO()
strip.save(buf, format='WebP', lossless=True)
b64 = base64.b64encode(buf.getvalue()).decode()

index_entries = ',\n    '.join(f'{level}: {i}' for i, (_, level) in enumerate(FRAMES))

ts = f"""// Auto-generated by scripts/build-spinner.py, do not edit manually.

export const KARMA_STRIP_WEBP = "{b64}";

export const KARMA_STRIP_META = {{
  frameSize: {frame_size},
  frameCount: {len(FRAMES)},
  index: {{
    {index_entries},
  }},
}} as const;
"""

os.makedirs(os.path.dirname(OUTPUT_TS), exist_ok=True)
with open(OUTPUT_TS, 'w') as f:
    f.write(ts)

print(f'Strip: {frame_size}x{frame_size * len(FRAMES)}px  ({len(buf.getvalue())} B raw, {len(b64)} B base64)')
print(f'Written to {OUTPUT_TS}')
