// Auto-generated by scripts/build-spinner.py: do not edit manually.

export const KARMA_STRIP_WEBP = "UklGRrICAABXRUJQVlA4TKUCAAAve0EJEA8w//M///Mf8KDbbH88uXlpBlT2U+hjMHQZ119DleISHOpYiBS2AHVk0HfoFrjRhqJvGqD5BXPsrCqI6P8EcPUeW2J6YPFhzjyEDIrch7E09VYRmvyHIUk/KvGkK/DRcyg8gc+vV9LI/d7esBvfG6FBdTv49lobxVqs935weEEs1h3NH2A8bClDydRQrch18sa+xuHpIcN0Vcp0KTKlgCTocufepo1Dsx4YfsHiOktWfQmI9n3csfXQjOmmI1+nSvncne3Yhq+RxfAlPYwNqu4u+D3s2KYriUwPNQIkgD3sjVOJC/7zO7YFuSSaNQPKw4pnO/e/27FlWDVSYw/AiBdJAowaqhW5Lja+SzDvjJKGBxSu9971zMaKMP4MkKeDJvew7TdfrMV670fiBTLo8rAWMDKnZlS4JI3cf7UVGd8rQJODmYEVLmPjBNLUraTQJUFVgpEAcaWVh5yk2CR5igQ9QomPlaqkcORoBiXwxSn2BpJg/y4gTd1KykgyquTpEWrg5ig+pKSR+6+24qToNtLUAiNB9deyFuu9H6FTxYGeijHziRd8Q7GH1FCtyHXfXMvcMCKRtc50qkGMwMbD+tE8ytOd8S1S7HBm985XXwKiuepH4gXL2Jc0PCWw0W0kpq1wCuOi+YwXZGNfYw8U40CTnjHDDEh62Np4UZKxb9YMUo1U5Y+Zflwpb7yo0dj3UCMsGSjBpD2kHLXbtPGimbEfviSYCjCM00v5VKhW3rvu2/fxhq2HiE1Hhi7Hw0/Ve9d9v7MXbMPvsQULauYqxVps936EUcNg392hhBu44cpGSSOPH23FN8X329iYLXwBX1wLkKS3Skq4JnvOkH8KTx9haQrFFaEqQJfjcWcemRmGAXJQM4/cY4t01xxwAxBPAQA=";

export const KARMA_STRIP_META = {
  frameSize: 38,
  frameCount: 10,
  index: {
    1: 0,
    2: 1,
    3: 2,
    4: 3,
    5: 4,
    6: 5,
    7: 6,
    8: 7,
    9: 8,
    10: 9,
  },
} as const;
